#pragma once

static const char kRenderWgslSource[] =
    "struct Globals {\n"
    "  viewProj    : mat4x4f,\n"
    "  viewport    : vec2f,\n"
    "  edgeWidthPx : f32,\n"
    "  nodeColor   : vec4f,\n"
    "  edgeColor   : vec4f,\n"
    "}\n"
    "\n"
    "@group(0) @binding(0) var<uniform> G : Globals;\n"
    "@group(0) @binding(1) var<storage, read> positions : array<f32>;\n"
    "@group(0) @binding(2) var<storage, read> nodeIds   : array<u32>;\n"
    "@group(0) @binding(3) var<storage, read> edges     : array<u32>;\n"
    "@group(0) @binding(4) var<storage, read> radii     : array<f32>;\n"
    "\n"
    "fn getPos(i : u32) -> vec2f {\n"
    "  return vec2f(positions[i * 2u], positions[i * 2u + 1u]);\n"
    "}\n"
    "\n"
    "const CORNERS = array<vec2f, 6>(\n"
    "  vec2f(-1.0, -1.0), vec2f(1.0, -1.0), vec2f(1.0, 1.0),\n"
    "  vec2f(-1.0, -1.0), vec2f(1.0, 1.0), vec2f(-1.0, 1.0));\n"
    "\n"
    "struct NodeOut {\n"
    "  @builtin(position) clip : vec4f,\n"
    "  @location(0) local : vec2f,\n"
    "  @location(1) @interpolate(flat) radius : f32,\n"
    "}\n"
    "\n"
    "@vertex\n"
    "fn vsNode(@builtin(vertex_index) vid : u32,\n"
    "          @builtin(instance_index) iid : u32) -> NodeOut {\n"
    "  let corner = CORNERS[vid];\n"
    "  let id = nodeIds[iid];\n"
    "  let radius = radii[id];\n"
    "  var clip = G.viewProj * vec4f(getPos(id), 0.0, 1.0);\n"
    "  let quadPx = radius + 1.0;\n"
    "  let local = corner * quadPx;\n"
    "  clip = vec4f(clip.xy + local * 2.0 / G.viewport * clip.w, clip.zw);\n"
    "  return NodeOut(clip, local, radius);\n"
    "}\n"
    "\n"
    "@fragment\n"
    "fn fsNode(in : NodeOut) -> @location(0) vec4f {\n"
    "  let sdf = length(in.local) - in.radius;\n"
    "  let coverage = 1.0 - smoothstep(-1.0, 1.0, sdf);\n"
    "  if (coverage <= 0.0) { discard; }\n"
    "  return vec4f(G.nodeColor.rgb, G.nodeColor.a * coverage);\n"
    "}\n"
    "\n"
    "struct EdgeOut {\n"
    "  @builtin(position) clip : vec4f,\n"
    "  @location(0) across : f32,\n"
    "}\n"
    "\n"
    "@vertex\n"
    "fn vsEdge(@builtin(vertex_index) vid : u32,\n"
    "          @builtin(instance_index) iid : u32) -> EdgeOut {\n"
    "  let a = edges[iid * 2u];\n"
    "  let b = edges[iid * 2u + 1u];\n"
    "  var clipA = G.viewProj * vec4f(getPos(a), 0.0, 1.0);\n"
    "  var clipB = G.viewProj * vec4f(getPos(b), 0.0, 1.0);\n"
    "  clipA.w = max(clipA.w, 1e-4);\n"
    "  clipB.w = max(clipB.w, 1e-4);\n"
    "\n"
    "  let screenA = clipA.xy / clipA.w * G.viewport * 0.5;\n"
    "  let screenB = clipB.xy / clipB.w * G.viewport * 0.5;\n"
    "  var dir = screenB - screenA;\n"
    "  let len = length(dir);\n"
    "  if (len < 1e-6) { dir = vec2f(1.0, 0.0); } else { dir = dir / len; }\n"
    "  let normal = vec2f(-dir.y, dir.x);\n"
    "\n"
    "  var end = 0.0;\n"
    "  if (vid == 1u || vid == 2u || vid == 4u) { end = 1.0; }\n"
    "  var side = -1.0;\n"
    "  if (vid == 2u || vid == 4u || vid == 5u) { side = 1.0; }\n"
    "\n"
    "  let clipEnd = mix(clipA, clipB, end);\n"
    "  let halfWidth = G.edgeWidthPx * 0.5 + 0.5;\n"
    "  let screen = mix(screenA, screenB, end) + normal * side * halfWidth;\n"
    "  let clip = vec4f(screen * 2.0 / G.viewport * clipEnd.w, clipEnd.zw);\n"
    "  return EdgeOut(clip, side * halfWidth);\n"
    "}\n"
    "\n"
    "@fragment\n"
    "fn fsEdge(in : EdgeOut) -> @location(0) vec4f {\n"
    "  let halfWidth = G.edgeWidthPx * 0.5;\n"
    "  let coverage = 1.0 - smoothstep(halfWidth - 0.5, halfWidth + 0.5, abs(in.across));\n"
    "  if (coverage <= 0.0) { discard; }\n"
    "  return vec4f(G.edgeColor.rgb, G.edgeColor.a * coverage);\n"
    "}\n";
